# Generated by Django 5.0.4 on 2024-04-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(default=0, verbose_name='Цена за подписку')),
                ('subscription_date', models.DateTimeField(verbose_name='Дата первого списания')),
                ('period', models.IntegerField(default=0, verbose_name='Период списания')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Подписка',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Cлаг')),
            ],
            options={
                'verbose_name': 'Категории',
            },
        ),
    ]
